import {
  Archive,
  Armchair,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  Award,
  Ban,
  Banknote,
  Bell,
  BellOff,
  Bitcoin,
  Blocks,
  Bookmark,
  Bot,
  Braces,
  BrainCircuit,
  BriefcaseBusiness,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Circle,
  CircleCheck,
  CircleHelp,
  CircleMinus,
  CircleX,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  Contact,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Dices,
  DollarSign,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileDiff,
  FilePenLine,
  FilePlus,
  FileText,
  FileUp,
  Fingerprint,
  Folder,
  FolderOpen,
  Gamepad2,
  Globe,
  GraduationCap,
  GripVertical,
  HardDrive,
  Headset,
  Heart,
  Hexagon,
  History,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Laptop,
  Layers,
  Link,
  ListFilter,
  LoaderCircle,
  LockKeyhole,
  LockKeyholeOpen,
  LogOut,
  Mail,
  MessageCircle,
  MessagesSquare,
  Microscope,
  Monitor,
  MonitorSmartphone,
  Moon,
  Network,
  Package,
  Palette,
  Pencil,
  Phone,
  PiggyBank,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  RotateCcwKey,
  Router,
  ScanQrCode,
  Search,
  SearchX,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shapes,
  Shield,
  ShieldCheck,
  ShieldUser,
  ShieldX,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquareArrowOutUpRight,
  SquareCode,
  Star,
  StickyNote,
  Sun,
  Tag,
  Terminal,
  TimerOff,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserRoundCog,
  UserRoundPlus,
  UserRoundX,
  Users,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Keep persisted Material-style names stable; bundle only the SVGs used by the UI.
export const ICON_GLYPHS: Readonly<Record<string, LucideIcon>> = {
  filter_alt_off: ListFilter,
  image_search: Image,
  mail_off: Mail,
  person_search: User,
  radio_button_unchecked: Circle,

  account_balance: Landmark,
  add: Plus,
  admin_panel_settings: ShieldUser,
  android: Bot,
  api: Blocks,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  north_east: ArrowUpRight,
  article: FileText,
  assistant: Sparkles,
  attach_money: DollarSign,
  auto_mode: RefreshCw,
  autorenew: RefreshCw,
  badge: Contact,
  batch_prediction: Layers,
  biotech: Microscope,
  block: Ban,
  bolt: Zap,
  bookmark: Bookmark,
  business: Building,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  cancel: CircleX,
  casino: Dices,
  category: Shapes,
  chat: MessageCircle,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud: Cloud,
  cloud_upload: CloudUpload,
  code: Code,
  computer: Monitor,
  content_copy: Copy,
  corporate_fare: Building2,
  credit_card: CreditCard,
  currency_bitcoin: Bitcoin,
  dark_mode: Moon,
  data_object: Braces,
  database: Database,
  delete: Trash2,
  delete_forever: Trash2,
  developer_mode: SquareCode,
  devices: MonitorSmartphone,
  difference: FileDiff,
  dns: Server,
  domain: Building2,
  done_all: CheckCheck,
  download: Download,
  drag_indicator: GripVertical,
  edit: Pencil,
  edit_note: FilePenLine,
  email: Mail,
  encrypted: ShieldCheck,
  enhanced_encryption: LockKeyhole,
  error: CircleAlert,
  event: Calendar,
  event_seat: Armchair,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  extension: Puzzle,
  favorite: Heart,
  file_download: Download,
  file_upload: Upload,
  filter_list: ListFilter,
  fingerprint: Fingerprint,
  folder: Folder,
  folder_open: FolderOpen,
  forum: MessagesSquare,
  forward_to_inbox: Mail,
  gpp_bad: ShieldX,
  group: Users,
  group_add: UserRoundPlus,
  help: CircleHelp,
  history: History,
  home: House,
  hourglass_empty: Hourglass,
  how_to_reg: UserCheck,
  hub: Network,
  image: Image,
  inbox: Inbox,
  info: Info,
  inventory: Package,
  key: KeyRound,
  key_off: KeyRound,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  label: Tag,
  language: Globe,
  laptop: Laptop,
  light_mode: Sun,
  link: Link,
  lock: LockKeyhole,
  lock_clock: LockKeyhole,
  lock_open: LockKeyholeOpen,
  lock_reset: RotateCcwKey,
  logout: LogOut,
  mail: Mail,
  manage_accounts: UserRoundCog,
  manage_search: ListFilter,
  memory: Cpu,
  more_horiz: Ellipsis,
  note_add: FilePlus,
  notes: StickyNote,
  notifications: Bell,
  notifications_off: BellOff,
  open_in_new: ExternalLink,
  outgoing_mail: Send,
  output: SquareArrowOutUpRight,
  palette: Palette,
  password: KeyRound,
  payments: Banknote,
  people: Users,
  person: User,
  person_add: UserPlus,
  person_off: UserRoundX,
  person_remove: UserMinus,
  phone: Phone,
  precision_manufacturing: Bot,
  progress_activity: LoaderCircle,
  psychology: BrainCircuit,
  public: Globe,
  qr_code_scanner: ScanQrCode,
  refresh: RefreshCw,
  remove_circle: CircleMinus,
  replay: RotateCcw,
  restore: History,
  router: Router,
  savings: PiggyBank,
  schedule: Clock,
  school: GraduationCap,
  search: Search,
  search_off: SearchX,
  security: ShieldCheck,
  settings: Settings,
  settings_suggest: Settings2,
  share: Share2,
  shield: Shield,
  shield_person: ShieldUser,
  smart_toy: Bot,
  smartphone: Smartphone,
  sort: ListFilter,
  sports_esports: Gamepad2,
  star: Star,
  sticky_note_2: StickyNote,
  storage: HardDrive,
  support_agent: Headset,
  swap_horiz: ArrowLeftRight,
  sync: RefreshCw,
  task_alt: CircleCheck,
  terminal: Terminal,
  text_fields: Type,
  timer_off: TimerOff,
  token: Hexagon,
  tune: SlidersHorizontal,
  upload: Upload,
  upload_file: FileUp,
  verified_user: ShieldCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  vpn_key: KeyRound,
  wallet: Wallet,
  warning: TriangleAlert,
  work: BriefcaseBusiness,
  workspace_premium: Award,
}
