/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVaultsRouteImport } from './routes/_authenticated/vaults'
import { Route as AuthenticatedUnlockRouteImport } from './routes/_authenticated/unlock'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedVaultsVaultIdRouteImport } from './routes/_authenticated/vaults_.$vaultId'
import { Route as AuthenticatedApiKeysKeyIdRouteImport } from './routes/_authenticated/api-keys_.$keyId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents_.$agentId'
import { Route as AuthenticatedVaultsVaultIdSettingsRouteImport } from './routes/_authenticated/vaults_.$vaultId_.settings'
import { Route as AuthenticatedVaultsVaultIdEntriesEntryIdRouteImport } from './routes/_authenticated/vaults_.$vaultId_.entries_.$entryId'

const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsRoute = AuthenticatedVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnlockRoute = AuthenticatedUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsVaultIdRoute =
  AuthenticatedVaultsVaultIdRouteImport.update({
    id: '/vaults_/$vaultId',
    path: '/vaults/$vaultId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiKeysKeyIdRoute =
  AuthenticatedApiKeysKeyIdRouteImport.update({
    id: '/api-keys_/$keyId',
    path: '/api-keys/$keyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents_/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVaultsVaultIdSettingsRoute =
  AuthenticatedVaultsVaultIdSettingsRouteImport.update({
    id: '/vaults_/$vaultId_/settings',
    path: '/vaults/$vaultId/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVaultsVaultIdEntriesEntryIdRoute =
  AuthenticatedVaultsVaultIdEntriesEntryIdRouteImport.update({
    id: '/vaults_/$vaultId_/entries_/$entryId',
    path: '/vaults/$vaultId/entries/$entryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/unlock': typeof AuthenticatedUnlockRoute
  '/vaults': typeof AuthenticatedVaultsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/api-keys/$keyId': typeof AuthenticatedApiKeysKeyIdRoute
  '/vaults/$vaultId': typeof AuthenticatedVaultsVaultIdRoute
  '/vaults/$vaultId/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
  '/vaults/$vaultId/entries/$entryId': typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/unlock': typeof AuthenticatedUnlockRoute
  '/vaults': typeof AuthenticatedVaultsRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/api-keys/$keyId': typeof AuthenticatedApiKeysKeyIdRoute
  '/vaults/$vaultId': typeof AuthenticatedVaultsVaultIdRoute
  '/vaults/$vaultId/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
  '/vaults/$vaultId/entries/$entryId': typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/unlock': typeof AuthenticatedUnlockRoute
  '/_authenticated/vaults': typeof AuthenticatedVaultsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents_/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/api-keys_/$keyId': typeof AuthenticatedApiKeysKeyIdRoute
  '/_authenticated/vaults_/$vaultId': typeof AuthenticatedVaultsVaultIdRoute
  '/_authenticated/vaults_/$vaultId_/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
  '/_authenticated/vaults_/$vaultId_/entries_/$entryId': typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recovery'
    | '/agents'
    | '/api-keys'
    | '/approvals'
    | '/billing'
    | '/settings'
    | '/unlock'
    | '/vaults'
    | '/agents/$agentId'
    | '/api-keys/$keyId'
    | '/vaults/$vaultId'
    | '/vaults/$vaultId/settings'
    | '/vaults/$vaultId/entries/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recovery'
    | '/agents'
    | '/api-keys'
    | '/approvals'
    | '/billing'
    | '/settings'
    | '/unlock'
    | '/vaults'
    | '/'
    | '/agents/$agentId'
    | '/api-keys/$keyId'
    | '/vaults/$vaultId'
    | '/vaults/$vaultId/settings'
    | '/vaults/$vaultId/entries/$entryId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/recovery'
    | '/_authenticated/agents'
    | '/_authenticated/api-keys'
    | '/_authenticated/approvals'
    | '/_authenticated/billing'
    | '/_authenticated/settings'
    | '/_authenticated/unlock'
    | '/_authenticated/vaults'
    | '/_authenticated/'
    | '/_authenticated/agents_/$agentId'
    | '/_authenticated/api-keys_/$keyId'
    | '/_authenticated/vaults_/$vaultId'
    | '/_authenticated/vaults_/$vaultId_/settings'
    | '/_authenticated/vaults_/$vaultId_/entries_/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoveryRoute: typeof RecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults': {
      id: '/_authenticated/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AuthenticatedVaultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/unlock': {
      id: '/_authenticated/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof AuthenticatedUnlockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults_/$vaultId': {
      id: '/_authenticated/vaults_/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys_/$keyId': {
      id: '/_authenticated/api-keys_/$keyId'
      path: '/api-keys/$keyId'
      fullPath: '/api-keys/$keyId'
      preLoaderRoute: typeof AuthenticatedApiKeysKeyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents_/$agentId': {
      id: '/_authenticated/agents_/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults_/$vaultId_/settings': {
      id: '/_authenticated/vaults_/$vaultId_/settings'
      path: '/vaults/$vaultId/settings'
      fullPath: '/vaults/$vaultId/settings'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults_/$vaultId_/entries_/$entryId': {
      id: '/_authenticated/vaults_/$vaultId_/entries_/$entryId'
      path: '/vaults/$vaultId/entries/$entryId'
      fullPath: '/vaults/$vaultId/entries/$entryId'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdEntriesEntryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUnlockRoute: typeof AuthenticatedUnlockRoute
  AuthenticatedVaultsRoute: typeof AuthenticatedVaultsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedApiKeysKeyIdRoute: typeof AuthenticatedApiKeysKeyIdRoute
  AuthenticatedVaultsVaultIdRoute: typeof AuthenticatedVaultsVaultIdRoute
  AuthenticatedVaultsVaultIdSettingsRoute: typeof AuthenticatedVaultsVaultIdSettingsRoute
  AuthenticatedVaultsVaultIdEntriesEntryIdRoute: typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUnlockRoute: AuthenticatedUnlockRoute,
  AuthenticatedVaultsRoute: AuthenticatedVaultsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedApiKeysKeyIdRoute: AuthenticatedApiKeysKeyIdRoute,
  AuthenticatedVaultsVaultIdRoute: AuthenticatedVaultsVaultIdRoute,
  AuthenticatedVaultsVaultIdSettingsRoute:
    AuthenticatedVaultsVaultIdSettingsRoute,
  AuthenticatedVaultsVaultIdEntriesEntryIdRoute:
    AuthenticatedVaultsVaultIdEntriesEntryIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoveryRoute: RecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
