/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVaultsRouteImport } from './routes/_authenticated/vaults'
import { Route as AuthenticatedUnlockRouteImport } from './routes/_authenticated/unlock'
import { Route as AuthenticatedVaultsVaultIdRouteImport } from './routes/_authenticated/vaults.$vaultId'
import { Route as AuthenticatedVaultsVaultIdSettingsRouteImport } from './routes/_authenticated/vaults.$vaultId.settings'

const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsRoute = AuthenticatedVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnlockRoute = AuthenticatedUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsVaultIdRoute =
  AuthenticatedVaultsVaultIdRouteImport.update({
    id: '/$vaultId',
    path: '/$vaultId',
    getParentRoute: () => AuthenticatedVaultsRoute,
  } as any)
const AuthenticatedVaultsVaultIdSettingsRoute =
  AuthenticatedVaultsVaultIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedVaultsVaultIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/unlock': typeof AuthenticatedUnlockRoute
  '/vaults': typeof AuthenticatedVaultsRouteWithChildren
  '/vaults/$vaultId': typeof AuthenticatedVaultsVaultIdRouteWithChildren
  '/vaults/$vaultId/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/unlock': typeof AuthenticatedUnlockRoute
  '/vaults': typeof AuthenticatedVaultsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/vaults/$vaultId': typeof AuthenticatedVaultsVaultIdRouteWithChildren
  '/vaults/$vaultId/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/_authenticated/unlock': typeof AuthenticatedUnlockRoute
  '/_authenticated/vaults': typeof AuthenticatedVaultsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vaults/$vaultId': typeof AuthenticatedVaultsVaultIdRouteWithChildren
  '/_authenticated/vaults/$vaultId/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recovery'
    | '/unlock'
    | '/vaults'
    | '/vaults/$vaultId'
    | '/vaults/$vaultId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recovery'
    | '/unlock'
    | '/vaults'
    | '/'
    | '/vaults/$vaultId'
    | '/vaults/$vaultId/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/recovery'
    | '/_authenticated/unlock'
    | '/_authenticated/vaults'
    | '/_authenticated/'
    | '/_authenticated/vaults/$vaultId'
    | '/_authenticated/vaults/$vaultId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoveryRoute: typeof RecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults': {
      id: '/_authenticated/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AuthenticatedVaultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/unlock': {
      id: '/_authenticated/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof AuthenticatedUnlockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults/$vaultId': {
      id: '/_authenticated/vaults/$vaultId'
      path: '/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdRouteImport
      parentRoute: typeof AuthenticatedVaultsRoute
    }
    '/_authenticated/vaults/$vaultId/settings': {
      id: '/_authenticated/vaults/$vaultId/settings'
      path: '/settings'
      fullPath: '/vaults/$vaultId/settings'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdSettingsRouteImport
      parentRoute: typeof AuthenticatedVaultsVaultIdRoute
    }
  }
}

interface AuthenticatedVaultsVaultIdRouteChildren {
  AuthenticatedVaultsVaultIdSettingsRoute: typeof AuthenticatedVaultsVaultIdSettingsRoute
}

const AuthenticatedVaultsVaultIdRouteChildren: AuthenticatedVaultsVaultIdRouteChildren =
  {
    AuthenticatedVaultsVaultIdSettingsRoute:
      AuthenticatedVaultsVaultIdSettingsRoute,
  }

const AuthenticatedVaultsVaultIdRouteWithChildren =
  AuthenticatedVaultsVaultIdRoute._addFileChildren(
    AuthenticatedVaultsVaultIdRouteChildren,
  )

interface AuthenticatedVaultsRouteChildren {
  AuthenticatedVaultsVaultIdRoute: typeof AuthenticatedVaultsVaultIdRouteWithChildren
}

const AuthenticatedVaultsRouteChildren: AuthenticatedVaultsRouteChildren = {
  AuthenticatedVaultsVaultIdRoute: AuthenticatedVaultsVaultIdRouteWithChildren,
}

const AuthenticatedVaultsRouteWithChildren =
  AuthenticatedVaultsRoute._addFileChildren(AuthenticatedVaultsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedUnlockRoute: typeof AuthenticatedUnlockRoute
  AuthenticatedVaultsRoute: typeof AuthenticatedVaultsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUnlockRoute: AuthenticatedUnlockRoute,
  AuthenticatedVaultsRoute: AuthenticatedVaultsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoveryRoute: RecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
