/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DevToastsRouteImport } from './routes/dev-toasts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedUnlockRouteImport } from './routes/_authenticated/unlock'
import { Route as AuthenticatedVaultsRouteImport } from './routes/_authenticated/vaults'
import { Route as AuthenticatedAgentPairingPairingIdRouteImport } from './routes/_authenticated/agent-pairing.$pairingId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents_.$agentId'
import { Route as AuthenticatedApiKeysKeyIdRouteImport } from './routes/_authenticated/api-keys_.$keyId'
import { Route as AuthenticatedInvitationsAcceptRouteImport } from './routes/_authenticated/invitations.accept'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings.api-keys'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings.billing'
import { Route as AuthenticatedSettingsDataExportRouteImport } from './routes/_authenticated/settings.data-export'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings.general'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings.permissions'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedVaultsVaultIdRouteImport } from './routes/_authenticated/vaults_.$vaultId'
import { Route as AuthenticatedSettingsApiKeysKeyIdRouteImport } from './routes/_authenticated/settings.api-keys_.$keyId'
import { Route as AuthenticatedSettingsPermissionsRoleIdRouteImport } from './routes/_authenticated/settings.permissions_.$roleId'
import { Route as AuthenticatedSettingsTeamMemberIdRouteImport } from './routes/_authenticated/settings.team_.$memberId'
import { Route as AuthenticatedVaultsVaultIdGrantsRouteImport } from './routes/_authenticated/vaults_.$vaultId_.grants'
import { Route as AuthenticatedVaultsVaultIdSettingsRouteImport } from './routes/_authenticated/vaults_.$vaultId_.settings'
import { Route as AuthenticatedSettingsTeamInvitationsInvitationIdRouteImport } from './routes/_authenticated/settings.team_.invitations_.$invitationId'
import { Route as AuthenticatedVaultsVaultIdEntriesEntryIdRouteImport } from './routes/_authenticated/vaults_.$vaultId_.entries_.$entryId'
import { Route as AuthenticatedVaultsVaultIdGrantsGrantIdRouteImport } from './routes/_authenticated/vaults_.$vaultId_.grants_.$grantId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToastsRoute = DevToastsRouteImport.update({
  id: '/dev-toasts',
  path: '/dev-toasts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnlockRoute = AuthenticatedUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsRoute = AuthenticatedVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentPairingPairingIdRoute =
  AuthenticatedAgentPairingPairingIdRouteImport.update({
    id: '/agent-pairing/$pairingId',
    path: '/agent-pairing/$pairingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents_/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiKeysKeyIdRoute =
  AuthenticatedApiKeysKeyIdRouteImport.update({
    id: '/api-keys_/$keyId',
    path: '/api-keys/$keyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvitationsAcceptRoute =
  AuthenticatedInvitationsAcceptRouteImport.update({
    id: '/invitations/accept',
    path: '/invitations/accept',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDataExportRoute =
  AuthenticatedSettingsDataExportRouteImport.update({
    id: '/data-export',
    path: '/data-export',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedVaultsVaultIdRoute =
  AuthenticatedVaultsVaultIdRouteImport.update({
    id: '/vaults_/$vaultId',
    path: '/vaults/$vaultId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiKeysKeyIdRoute =
  AuthenticatedSettingsApiKeysKeyIdRouteImport.update({
    id: '/api-keys_/$keyId',
    path: '/api-keys/$keyId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoleIdRoute =
  AuthenticatedSettingsPermissionsRoleIdRouteImport.update({
    id: '/permissions_/$roleId',
    path: '/permissions/$roleId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamMemberIdRoute =
  AuthenticatedSettingsTeamMemberIdRouteImport.update({
    id: '/team_/$memberId',
    path: '/team/$memberId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedVaultsVaultIdGrantsRoute =
  AuthenticatedVaultsVaultIdGrantsRouteImport.update({
    id: '/vaults_/$vaultId_/grants',
    path: '/vaults/$vaultId/grants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVaultsVaultIdSettingsRoute =
  AuthenticatedVaultsVaultIdSettingsRouteImport.update({
    id: '/vaults_/$vaultId_/settings',
    path: '/vaults/$vaultId/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTeamInvitationsInvitationIdRoute =
  AuthenticatedSettingsTeamInvitationsInvitationIdRouteImport.update({
    id: '/team_/invitations_/$invitationId',
    path: '/team/invitations/$invitationId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedVaultsVaultIdEntriesEntryIdRoute =
  AuthenticatedVaultsVaultIdEntriesEntryIdRouteImport.update({
    id: '/vaults_/$vaultId_/entries_/$entryId',
    path: '/vaults/$vaultId/entries/$entryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVaultsVaultIdGrantsGrantIdRoute =
  AuthenticatedVaultsVaultIdGrantsGrantIdRouteImport.update({
    id: '/vaults_/$vaultId_/grants_/$grantId',
    path: '/vaults/$vaultId/grants/$grantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/dev-toasts': typeof DevToastsRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/unlock': typeof AuthenticatedUnlockRoute
  '/vaults': typeof AuthenticatedVaultsRoute
  '/agent-pairing/$pairingId': typeof AuthenticatedAgentPairingPairingIdRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/api-keys/$keyId': typeof AuthenticatedApiKeysKeyIdRoute
  '/invitations/accept': typeof AuthenticatedInvitationsAcceptRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/data-export': typeof AuthenticatedSettingsDataExportRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/vaults/$vaultId': typeof AuthenticatedVaultsVaultIdRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/api-keys/$keyId': typeof AuthenticatedSettingsApiKeysKeyIdRoute
  '/settings/permissions/$roleId': typeof AuthenticatedSettingsPermissionsRoleIdRoute
  '/settings/team/$memberId': typeof AuthenticatedSettingsTeamMemberIdRoute
  '/vaults/$vaultId/grants': typeof AuthenticatedVaultsVaultIdGrantsRoute
  '/vaults/$vaultId/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
  '/settings/team/invitations/$invitationId': typeof AuthenticatedSettingsTeamInvitationsInvitationIdRoute
  '/vaults/$vaultId/entries/$entryId': typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
  '/vaults/$vaultId/grants/$grantId': typeof AuthenticatedVaultsVaultIdGrantsGrantIdRoute
}
export interface FileRoutesByTo {
  '/dev-toasts': typeof DevToastsRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/team': typeof AuthenticatedTeamRoute
  '/unlock': typeof AuthenticatedUnlockRoute
  '/vaults': typeof AuthenticatedVaultsRoute
  '/': typeof AuthenticatedIndexRoute
  '/agent-pairing/$pairingId': typeof AuthenticatedAgentPairingPairingIdRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/api-keys/$keyId': typeof AuthenticatedApiKeysKeyIdRoute
  '/invitations/accept': typeof AuthenticatedInvitationsAcceptRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/data-export': typeof AuthenticatedSettingsDataExportRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/vaults/$vaultId': typeof AuthenticatedVaultsVaultIdRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/api-keys/$keyId': typeof AuthenticatedSettingsApiKeysKeyIdRoute
  '/settings/permissions/$roleId': typeof AuthenticatedSettingsPermissionsRoleIdRoute
  '/settings/team/$memberId': typeof AuthenticatedSettingsTeamMemberIdRoute
  '/vaults/$vaultId/grants': typeof AuthenticatedVaultsVaultIdGrantsRoute
  '/vaults/$vaultId/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
  '/settings/team/invitations/$invitationId': typeof AuthenticatedSettingsTeamInvitationsInvitationIdRoute
  '/vaults/$vaultId/entries/$entryId': typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
  '/vaults/$vaultId/grants/$grantId': typeof AuthenticatedVaultsVaultIdGrantsGrantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dev-toasts': typeof DevToastsRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/unlock': typeof AuthenticatedUnlockRoute
  '/_authenticated/vaults': typeof AuthenticatedVaultsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agent-pairing/$pairingId': typeof AuthenticatedAgentPairingPairingIdRoute
  '/_authenticated/agents_/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/api-keys_/$keyId': typeof AuthenticatedApiKeysKeyIdRoute
  '/_authenticated/invitations/accept': typeof AuthenticatedInvitationsAcceptRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/data-export': typeof AuthenticatedSettingsDataExportRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/vaults_/$vaultId': typeof AuthenticatedVaultsVaultIdRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/api-keys_/$keyId': typeof AuthenticatedSettingsApiKeysKeyIdRoute
  '/_authenticated/settings/permissions_/$roleId': typeof AuthenticatedSettingsPermissionsRoleIdRoute
  '/_authenticated/settings/team_/$memberId': typeof AuthenticatedSettingsTeamMemberIdRoute
  '/_authenticated/vaults_/$vaultId_/grants': typeof AuthenticatedVaultsVaultIdGrantsRoute
  '/_authenticated/vaults_/$vaultId_/settings': typeof AuthenticatedVaultsVaultIdSettingsRoute
  '/_authenticated/settings/team_/invitations_/$invitationId': typeof AuthenticatedSettingsTeamInvitationsInvitationIdRoute
  '/_authenticated/vaults_/$vaultId_/entries_/$entryId': typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
  '/_authenticated/vaults_/$vaultId_/grants_/$grantId': typeof AuthenticatedVaultsVaultIdGrantsGrantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-toasts'
    | '/login'
    | '/recovery'
    | '/register'
    | '/verify-email'
    | '/agents'
    | '/api-keys'
    | '/approvals'
    | '/audit'
    | '/billing'
    | '/inbox'
    | '/security'
    | '/settings'
    | '/team'
    | '/unlock'
    | '/vaults'
    | '/agent-pairing/$pairingId'
    | '/agents/$agentId'
    | '/api-keys/$keyId'
    | '/invitations/accept'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/data-export'
    | '/settings/general'
    | '/settings/permissions'
    | '/settings/security'
    | '/settings/team'
    | '/vaults/$vaultId'
    | '/settings/'
    | '/settings/api-keys/$keyId'
    | '/settings/permissions/$roleId'
    | '/settings/team/$memberId'
    | '/vaults/$vaultId/grants'
    | '/vaults/$vaultId/settings'
    | '/settings/team/invitations/$invitationId'
    | '/vaults/$vaultId/entries/$entryId'
    | '/vaults/$vaultId/grants/$grantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev-toasts'
    | '/login'
    | '/recovery'
    | '/register'
    | '/verify-email'
    | '/agents'
    | '/api-keys'
    | '/approvals'
    | '/audit'
    | '/billing'
    | '/inbox'
    | '/security'
    | '/team'
    | '/unlock'
    | '/vaults'
    | '/'
    | '/agent-pairing/$pairingId'
    | '/agents/$agentId'
    | '/api-keys/$keyId'
    | '/invitations/accept'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/data-export'
    | '/settings/general'
    | '/settings/permissions'
    | '/settings/security'
    | '/settings/team'
    | '/vaults/$vaultId'
    | '/settings'
    | '/settings/api-keys/$keyId'
    | '/settings/permissions/$roleId'
    | '/settings/team/$memberId'
    | '/vaults/$vaultId/grants'
    | '/vaults/$vaultId/settings'
    | '/settings/team/invitations/$invitationId'
    | '/vaults/$vaultId/entries/$entryId'
    | '/vaults/$vaultId/grants/$grantId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/dev-toasts'
    | '/login'
    | '/recovery'
    | '/register'
    | '/verify-email'
    | '/_authenticated/agents'
    | '/_authenticated/api-keys'
    | '/_authenticated/approvals'
    | '/_authenticated/audit'
    | '/_authenticated/billing'
    | '/_authenticated/inbox'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/unlock'
    | '/_authenticated/vaults'
    | '/_authenticated/'
    | '/_authenticated/agent-pairing/$pairingId'
    | '/_authenticated/agents_/$agentId'
    | '/_authenticated/api-keys_/$keyId'
    | '/_authenticated/invitations/accept'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/data-export'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/team'
    | '/_authenticated/vaults_/$vaultId'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/api-keys_/$keyId'
    | '/_authenticated/settings/permissions_/$roleId'
    | '/_authenticated/settings/team_/$memberId'
    | '/_authenticated/vaults_/$vaultId_/grants'
    | '/_authenticated/vaults_/$vaultId_/settings'
    | '/_authenticated/settings/team_/invitations_/$invitationId'
    | '/_authenticated/vaults_/$vaultId_/entries_/$entryId'
    | '/_authenticated/vaults_/$vaultId_/grants_/$grantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DevToastsRoute: typeof DevToastsRoute
  LoginRoute: typeof LoginRoute
  RecoveryRoute: typeof RecoveryRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-toasts': {
      id: '/dev-toasts'
      path: '/dev-toasts'
      fullPath: '/dev-toasts'
      preLoaderRoute: typeof DevToastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/unlock': {
      id: '/_authenticated/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof AuthenticatedUnlockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults': {
      id: '/_authenticated/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AuthenticatedVaultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-pairing/$pairingId': {
      id: '/_authenticated/agent-pairing/$pairingId'
      path: '/agent-pairing/$pairingId'
      fullPath: '/agent-pairing/$pairingId'
      preLoaderRoute: typeof AuthenticatedAgentPairingPairingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents_/$agentId': {
      id: '/_authenticated/agents_/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys_/$keyId': {
      id: '/_authenticated/api-keys_/$keyId'
      path: '/api-keys/$keyId'
      fullPath: '/api-keys/$keyId'
      preLoaderRoute: typeof AuthenticatedApiKeysKeyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitations/accept': {
      id: '/_authenticated/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof AuthenticatedInvitationsAcceptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/data-export': {
      id: '/_authenticated/settings/data-export'
      path: '/data-export'
      fullPath: '/settings/data-export'
      preLoaderRoute: typeof AuthenticatedSettingsDataExportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/vaults_/$vaultId': {
      id: '/_authenticated/vaults_/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-keys_/$keyId': {
      id: '/_authenticated/settings/api-keys_/$keyId'
      path: '/api-keys/$keyId'
      fullPath: '/settings/api-keys/$keyId'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysKeyIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/permissions_/$roleId': {
      id: '/_authenticated/settings/permissions_/$roleId'
      path: '/permissions/$roleId'
      fullPath: '/settings/permissions/$roleId'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRoleIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/team_/$memberId': {
      id: '/_authenticated/settings/team_/$memberId'
      path: '/team/$memberId'
      fullPath: '/settings/team/$memberId'
      preLoaderRoute: typeof AuthenticatedSettingsTeamMemberIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/vaults_/$vaultId_/grants': {
      id: '/_authenticated/vaults_/$vaultId_/grants'
      path: '/vaults/$vaultId/grants'
      fullPath: '/vaults/$vaultId/grants'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdGrantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults_/$vaultId_/settings': {
      id: '/_authenticated/vaults_/$vaultId_/settings'
      path: '/vaults/$vaultId/settings'
      fullPath: '/vaults/$vaultId/settings'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team_/invitations_/$invitationId': {
      id: '/_authenticated/settings/team_/invitations_/$invitationId'
      path: '/team/invitations/$invitationId'
      fullPath: '/settings/team/invitations/$invitationId'
      preLoaderRoute: typeof AuthenticatedSettingsTeamInvitationsInvitationIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/vaults_/$vaultId_/entries_/$entryId': {
      id: '/_authenticated/vaults_/$vaultId_/entries_/$entryId'
      path: '/vaults/$vaultId/entries/$entryId'
      fullPath: '/vaults/$vaultId/entries/$entryId'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdEntriesEntryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults_/$vaultId_/grants_/$grantId': {
      id: '/_authenticated/vaults_/$vaultId_/grants_/$grantId'
      path: '/vaults/$vaultId/grants/$grantId'
      fullPath: '/vaults/$vaultId/grants/$grantId'
      preLoaderRoute: typeof AuthenticatedVaultsVaultIdGrantsGrantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsDataExportRoute: typeof AuthenticatedSettingsDataExportRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsApiKeysKeyIdRoute: typeof AuthenticatedSettingsApiKeysKeyIdRoute
  AuthenticatedSettingsPermissionsRoleIdRoute: typeof AuthenticatedSettingsPermissionsRoleIdRoute
  AuthenticatedSettingsTeamMemberIdRoute: typeof AuthenticatedSettingsTeamMemberIdRoute
  AuthenticatedSettingsTeamInvitationsInvitationIdRoute: typeof AuthenticatedSettingsTeamInvitationsInvitationIdRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsDataExportRoute: AuthenticatedSettingsDataExportRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsApiKeysKeyIdRoute:
    AuthenticatedSettingsApiKeysKeyIdRoute,
  AuthenticatedSettingsPermissionsRoleIdRoute:
    AuthenticatedSettingsPermissionsRoleIdRoute,
  AuthenticatedSettingsTeamMemberIdRoute:
    AuthenticatedSettingsTeamMemberIdRoute,
  AuthenticatedSettingsTeamInvitationsInvitationIdRoute:
    AuthenticatedSettingsTeamInvitationsInvitationIdRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedUnlockRoute: typeof AuthenticatedUnlockRoute
  AuthenticatedVaultsRoute: typeof AuthenticatedVaultsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentPairingPairingIdRoute: typeof AuthenticatedAgentPairingPairingIdRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedApiKeysKeyIdRoute: typeof AuthenticatedApiKeysKeyIdRoute
  AuthenticatedInvitationsAcceptRoute: typeof AuthenticatedInvitationsAcceptRoute
  AuthenticatedVaultsVaultIdRoute: typeof AuthenticatedVaultsVaultIdRoute
  AuthenticatedVaultsVaultIdGrantsRoute: typeof AuthenticatedVaultsVaultIdGrantsRoute
  AuthenticatedVaultsVaultIdSettingsRoute: typeof AuthenticatedVaultsVaultIdSettingsRoute
  AuthenticatedVaultsVaultIdEntriesEntryIdRoute: typeof AuthenticatedVaultsVaultIdEntriesEntryIdRoute
  AuthenticatedVaultsVaultIdGrantsGrantIdRoute: typeof AuthenticatedVaultsVaultIdGrantsGrantIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedUnlockRoute: AuthenticatedUnlockRoute,
  AuthenticatedVaultsRoute: AuthenticatedVaultsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentPairingPairingIdRoute:
    AuthenticatedAgentPairingPairingIdRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedApiKeysKeyIdRoute: AuthenticatedApiKeysKeyIdRoute,
  AuthenticatedInvitationsAcceptRoute: AuthenticatedInvitationsAcceptRoute,
  AuthenticatedVaultsVaultIdRoute: AuthenticatedVaultsVaultIdRoute,
  AuthenticatedVaultsVaultIdGrantsRoute: AuthenticatedVaultsVaultIdGrantsRoute,
  AuthenticatedVaultsVaultIdSettingsRoute:
    AuthenticatedVaultsVaultIdSettingsRoute,
  AuthenticatedVaultsVaultIdEntriesEntryIdRoute:
    AuthenticatedVaultsVaultIdEntriesEntryIdRoute,
  AuthenticatedVaultsVaultIdGrantsGrantIdRoute:
    AuthenticatedVaultsVaultIdGrantsGrantIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DevToastsRoute: DevToastsRoute,
  LoginRoute: LoginRoute,
  RecoveryRoute: RecoveryRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
